import os
import time
from dotenv import load_dotenv
from google import genai
from google.genai import errors as genai_errors

load_dotenv()

api_key = os.getenv("GEMINI_API_KEY")
client = genai.Client(api_key=api_key)


def generate_content_with_retry(model: str, contents: str, max_retries: int = 4, base_delay: float = 3.0):
    """
    Gemini API ko call karta hai, aur agar 503 (overloaded) ya koi
    temporary server error aaye, toh thoda ruk kar dobara try karta hai.
    Isse "high demand" wala error users tak nahi pahunchta.
    """
    last_error = None
    for attempt in range(max_retries):
        try:
            response = client.models.generate_content(
                model=model,
                contents=contents
            )
            return response
        except genai_errors.ServerError as e:
            last_error = e
            wait_time = base_delay * (attempt + 1)  # 3s, 6s, 9s, 12s
            print(f"Gemini overloaded (attempt {attempt + 1}/{max_retries}), retrying in {wait_time}s...")
            time.sleep(wait_time)
        except Exception as e:
            # Koi aur error ho toh turant raise karo, retry mat karo
            raise e

    # Saare retries fail ho gaye
    raise last_error


def analyze_gap(student_skills: str, required_skills: str, cgpa: float, min_cgpa: float, quiz_score, interview_status):
    prompt = f"""
You are a placement readiness advisor for a college student.

Student's current skills: {student_skills}
Company's required skills: {required_skills}
Student's CGPA: {cgpa} (required: {min_cgpa})
Quiz score: {quiz_score}
Interview status: {interview_status}

Give the student a short, friendly, encouraging improvement plan (3-4 bullet points max) 
to become placement-ready. Be specific and practical.
"""

    response = generate_content_with_retry(
        model="gemini-flash-latest",
        contents=prompt
    )

    return response.text

def generate_interview_question(role: str, student_skills: str, conversation_history: str):
    prompt = f"""
You are a friendly placement interviewer conducting a mock interview.

Role being interviewed for: {role}
Candidate's skills: {student_skills}
Conversation so far: {conversation_history if conversation_history else "This is the first question."}

Ask ONE relevant interview question for this role. Keep it natural and conversational.
Return ONLY the question, nothing else.
"""

    response = generate_content_with_retry(
        model="gemini-flash-latest",
        contents=prompt
    )

    return response.text.strip()


def generate_interview_feedback(conversation_history: str):
    prompt = f"""
You are reviewing a completed mock placement interview.

Full conversation:
{conversation_history}

Give a short feedback summary (2-3 sentences) covering the candidate's communication skills 
and technical depth. Be honest but encouraging.
"""

    response = generate_content_with_retry(
        model="gemini-flash-latest",
        contents=prompt
    )

    return response.text.strip()

def grade_quiz_answer(question_text: str, student_answer: str):
    prompt = f"""
You are grading a placement-readiness quiz answer.

Question: {question_text}
Student's Answer: {student_answer}

Score this answer from 0 to 10 based on correctness and clarity.
Return ONLY the number, nothing else. No explanation, no words, just the digit(s).
"""

    response = generate_content_with_retry(
        model="gemini-flash-latest",
        contents=prompt
    )

    result_text = response.text.strip()

    # Sirf number nikaalne ki koshish karo, agar AI ne extra text de diya
    try:
        score = int(''.join(filter(str.isdigit, result_text))[:2] or 0)
        score = min(score, 10)  # kabhi bhi 10 se zyada na ho
    except:
        score = 0

    return score



def detect_ai_generated_answer(question_text: str, student_answer: str):
    prompt = f"""
You are an expert at detecting whether a spoken interview answer was generated by an AI tool 
(like ChatGPT) versus spoken naturally by a real human candidate in a live interview.

Question asked: {question_text}
Candidate's answer: {student_answer}

Signs of AI-generated answers: overly polished/formal language, perfect structure with 
"firstly/secondly/in conclusion", no natural filler words or hesitation, generic textbook 
phrasing, unnaturally comprehensive for a spoken response.

Signs of genuine human answers: natural conversational tone, may have minor grammar slips, 
personal examples, some hesitation or informal phrasing.

Respond with ONLY one word: "SUSPICIOUS" if it looks AI-generated, or "GENUINE" if it looks 
like a natural human answer. No explanation, just one word.
"""

    response = generate_content_with_retry(
        model="gemini-flash-latest",
        contents=prompt
    )

    result = response.text.strip().upper()
    return "SUSPICIOUS" in result

def evaluate_interview_answer(question_text: str, student_answer: str):
    prompt = f"""
You are evaluating a candidate's answer in a placement interview.

Question asked: {question_text}
Candidate's answer: {student_answer}

Score this answer from 0 to 10 based on technical correctness, clarity, and relevance to the question.
Return ONLY the number, nothing else. No explanation, just the digit(s).
"""

    response = generate_content_with_retry(
        model="gemini-flash-latest",
        contents=prompt
    )

    result_text = response.text.strip()

    try:
        score = int(''.join(filter(str.isdigit, result_text))[:2] or 0)
        score = min(score, 10)
    except:
        score = 0

    return score